apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "clusterset-controller.labels" . | nindent 4 }}
  name: {{ include "clusterset-controller.authProxyServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "clusterset-controller.selectorLabels" . | nindent 4 }}
