# permissions to do viewer clustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clusterset-controller.runnerViewerRoleName" . }}
rules:
- apiGroups:
  - clusterset.mumo.co
  resources:
  - clustersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterset.mumo.co
  resources:
  - clustersets/status
  verbs:
  - get
